global:
  scrape_interval: 15s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'kasion-apps'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      # Only scrape containers with the kasion.scrape=true label
      - source_labels: [__meta_dockerswarm_task_label_kasion_scrape]
        action: keep
        regex: true
      # Use the container name as the instance label
      - source_labels: [__meta_dockerswarm_task_desired_state]
        action: replace
        target_label: state
        regex: running
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: job
        replacement: ${1}
      - source_labels: [__meta_dockerswarm_task_id]
        target_label: instance
